export enum HTTPStatusCode {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NO_CONTENT = 204,
    PARTIAL_CONTENT = 206,

    MOVED_PERMANENTLY = 301,
    FOUND = 302,
    NOT_MODIFIED = 304,
    TEMPORARY_REDIRECT = 307,
    PERMANENT_REDIRECT = 308,

    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    PAYMENT_REQUIRED = 402,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    CONFLICT = 409,
    GONE = 410,
    PRECONDITION_FAILED = 412,
    PAYLOAD_TOO_LARGE = 413,
    UNSUPPORTED_MEDIA_TYPE = 415,
    IM_A_TEAPOT = 418,
    UNPROCESSABLE_ENTITY = 422,
    TOO_EARLY = 425,
    TOO_MANY_REQUESTS = 429,
    REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
    UNAVAILABLE_FOR_LEGAL_REASONS = 451,

    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
    SERVICE_UNAVAILABLE = 503,
    GATEWAY_TIMEOUT = 504,
    NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export enum ErrorCode {
    INTERNAL = "INTERNAL",
    INCORRECTED_NICKNAME = "INCORRECTED_NICKNAME",
    INCORRECTED_PASSWORD = "INCORRECTED_PASSWORD",
    USER_ALREADY_EXIST = "USER_ALREADY_EXIST",
    USER_ENTITY_NOT_FOUND = "USER_ENTITY_NOT_FOUND",
    USERS_ENTITYES_NOT_FOUND = "USERS_ENTITYES_NOT_FOUND",
    BAD_CREDENTIALS = "BAD_CREDENTIALS",
    THREAD_NOT_FOUND = "THREAD_NOT_FOUND"
};

export enum ErrorMessage {
    INTERNAL = "Internal server error",
    INCORRECTED_NICKNAME = "Incorrected nickname",
    INCORRECTED_PASSWORD = "Incorrected password",
    USER_ALREADY_EXIST = "User already exist",
    USER_ENTITY_NOT_FOUND = "User entity not found",
    USERS_ENTITYES_NOT_FOUND = "Users entityes not found",
    BAD_CREDENTIALS = "Bad credentials",
    THREAD_NOT_FOUND = "Thread not found",
}

export enum ResponseMessage {
    OK = "OK",
}